# Generated by Django 2.2.3 on 2020-12-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='名称', max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': '测试表 1',
                'verbose_name_plural': '测试表 1',
            },
        ),
    ]
