# Generated by Django 2.2.3 on 2020-12-03 11:04

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel1',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
